// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP-P4rDtAS3DAjSBsctPG7xuhcRxNi0Bw',
    appId: '1:464531366295:web:f22b4ea0aed5bc26f264d2',
    messagingSenderId: '464531366295',
    projectId: 'score-54130',
    authDomain: 'score-54130.firebaseapp.com',
    storageBucket: 'score-54130.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-uvu0nIok5ArYTNWo_TOzXVYXcCL-2L8',
    appId: '1:464531366295:android:92ab7ae0bb1abac8f264d2',
    messagingSenderId: '464531366295',
    projectId: 'score-54130',
    storageBucket: 'score-54130.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBn1WOb8JVi29fU2qb_Tid6AxilH-aXJo',
    appId: '1:464531366295:ios:b2c79ba49ca0ca0af264d2',
    messagingSenderId: '464531366295',
    projectId: 'score-54130',
    storageBucket: 'score-54130.firebasestorage.app',
    iosBundleId: 'com.example.randandan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBn1WOb8JVi29fU2qb_Tid6AxilH-aXJo',
    appId: '1:464531366295:ios:b2c79ba49ca0ca0af264d2',
    messagingSenderId: '464531366295',
    projectId: 'score-54130',
    storageBucket: 'score-54130.firebasestorage.app',
    iosBundleId: 'com.example.randandan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCP-P4rDtAS3DAjSBsctPG7xuhcRxNi0Bw',
    appId: '1:464531366295:web:a784aecbedd79fdbf264d2',
    messagingSenderId: '464531366295',
    projectId: 'score-54130',
    authDomain: 'score-54130.firebaseapp.com',
    storageBucket: 'score-54130.firebasestorage.app',
  );
}
